"add_executable({0}\n"
" main.cpp\n"
")\n"
"\n"
"add_custom_command(TARGET {0} POST_BUILD\n"
"    COMMAND ${{CMAKE_COMMAND}} -E copy\n"
"        ${{CMAKE_BINARY_DIR}}/compile_commands.json\n"
"        ${{CMAKE_SOURCE_DIR}}/compile_commands.json\n"
"    COMMENT \"Add clangd to the base directory\")\n"
"\n"
"install(TARGETS {0} DESTINATION bin)\n"
