"add_executable({0}\n"
" main.cpp\n"
")\n"
"\n"
"# Adding libraries, delete if not needed.\n"
"# include(FetchContent)\n"
"# FetchContent_Declare()\n"
"# FetchContent_MakeAvailable()\n"
"#\n"
"# target_link_libraries({0} library_name)\n"
"\n"
"add_custom_command(TARGET {0} POST_BUILD\n"
"    COMMAND ${{CMAKE_COMMAND}} -E copy\n"
"        ${{CMAKE_BINARY_DIR}}/compile_commands.json\n"
"        ${{CMAKE_SOURCE_DIR}}/compile_commands.json\n"
"    COMMENT \"Add clangd to the base directory\")\n"
"\n"
"install(TARGETS {0} DESTINATION bin)\n"
